/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("mobility-kata-library")
}

dependencies {
//    api(project(":list"))
    testImplementation("org.assertj:assertj-core")
}
