/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm")
    id("com.diffplug.spotless")
}

val versionKtor by extra("2.3.0")

val versionApacheCommons by extra("1.10.0")
val versionJUnitJupiter by extra("5.9.2")
val versionAssertJ by extra("3.24.1")

repositories {
    mavenCentral()
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation("org.apache.commons:commons-text:$versionApacheCommons")

        implementation("io.ktor:ktor-server-core:$versionKtor")
        implementation("io.ktor:ktor-server-netty:$versionKtor")
        implementation("io.ktor:ktor-server-content-negotiation:$versionKtor")
        implementation("io.ktor:ktor-serialization-kotlinx-json:$versionKtor")
        implementation("io.ktor:ktor-server-call-logging:$versionKtor")

//        implementation("io.github.microutils:kotlin-logging-jvm:3.0.4")
//        implementation("ch.qos.logback:logback-classic:1.4.5")

        implementation("org.junit.jupiter:junit-jupiter:$versionJUnitJupiter")
        implementation("org.assertj:assertj-core:$versionAssertJ")
//        testImplementation("org.skyscreamer:jsonassert:1.5.1")
//        testImplementation("io.ktor:ktor-server-test-host:2.3.0")
    }
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter(versionJUnitJupiter)
        }
    }
}

spotless {
    kotlin { ktlint() }
    kotlinGradle { ktlint() }
}
